export const FETCH_MOVIES_REQUESTED = "FETCH_MOVIES_REQUESTED";
export const FETCH_MOVIES_SUCCEEDED = "FETCH_MOVIES_SUCCEEDED";
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED";
export const FILTER_MOVIES_BY_GENRE = "FILTER_MOVIES_BY_GENRE";
export const FILTER_MOVIES_BY_LANGUAGE = "FILTER_MOVIES_BY_LANGUAGE";
export const FILTER_MOVIES = "FILTER_MOVIES";